### PR TITLE
Update React dependencies

### LINKED ISSUE #26: SocketClient Component is outdated. Use Socket Component instead
**Current Situation**
I figured out that SocketClientComponent is outdated. So we should get rid of this.

**Expected Situation**
* We should use SocketComponent instead
* get also rid of DNS resolver.

### PR DESCRIPTION
**Pull request by jjok**
Closes #26

### CODE REVIEW

**Comment by jjok** [comment]
I don't think the `Connector` needs to implement the React `ConnectorInterface`. I've changed it so that you pass a `ConnectorInterface` into it. This means you don't need a separate `SecureConnector`, so I'mm removed that.

I think we should rename `Connector` to `Client`.

I refactored the connection stuff in `Connector`. I'm trying to remember why...

I need to fix the tests.

**Comment by jjok** [comment]
It's a work-in-progress. It needs some tidying up.

**Comment by oliverlorenz** [comment]
Do you waiting for me here?

**Comment by jjok** [comment]
If you're happy with the changes I've made so far, and the things I mentioned in above, then I'll go ahead and finish it off.

**Comment by jjok** [comment]
Done. There are still some outdated dev dependencies, which I think will mean dropping support for old versions of PHP. I might do that as a separate thing.

**Comment by oliverlorenz** [comment]
Is this still Work in Progress, or are you finished with that? :slightly_smiling_face:

**Comment by oliverlorenz** [comment]
If its not super necessary I would stick the the versions for the moment. I will merge that :smile: Thank you again!

**Pull request merged**
